export const Routes = {
  BottomTabContainer: 'BottomTabContainer',
  AuthStackContainer: 'AuthStackContainer',
  HomeStackContainer: 'HomeStackContainer',
  SearchStackContainer: 'SearchStackContainer',
  MyJobsStackContainer: 'MyJobsStackContainer',
  TimeCardStackContainer: 'TimeCardStackContainer',
  DrawerStackContainer: 'DrawerStackContainer',
  Welcome: 'Welcome',
  SignIn: 'SignIn',
  SignUp: 'SignUp',
  PopularCities: 'PopularCities',
  JobDetail: 'JobDetail',
  SuggestedJobs: 'SuggestedJobs',
  Home: 'Home',
  Search: 'Search',
  MyJobs: 'MyJobs',
  TimeCard: 'TimeCard',
};
